//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageCharacteristicsData
    {
        public int Id { get; set; }
        public int ImageID { get; set; }
        public string CharacteristicID { get; set; }
        public int CharacteristicValue { get; set; }
    }
}
